### ISSUE TITLE
Widget builder file picker filepath unused

### ISSUE THREAD

**Issue by Saerith** [BioDepot/BioDepot-workflow-builder#10]
When registering a new widget, the user is prompted to navigate to and select the json and python file for the widget. The builder will throw an error if the json file is not in the json folder. 
 
If the widget builder is already looking for `biodepot/User/json/myfile.json`, does it need to be prompted for by the file picker?
Otherwise, the widget builder should use the file path given by the file picker.

**Comment by lhhunghimself** [comment]
This is all being changed the next commit. The user will simply be asked to point to the widget directory where the widget files (json, py) reside. I've been meaning to change this so that all the files are in a single directory with the widget name. This allows us to easily add widget specific files such as a widget state file which will allow the widget builder to directly load and edit any widget.

**Comment by lhhunghimself** [comment]
The process has been simplified. I still need to grey out the buttons/add some animation to show that they have been clicked.
