### ISSUE TITLE
The tool is working only in one instance

### ISSUE THREAD

**Issue by pushkarbajaj9** [BioDepot/BioDepot-workflow-builder#18]
The tool if run by the given docker run command in the documentation runs only one instance of the tool.That is if the tool is open in any machine or any one browser of the machine, the other machine or browser cannot open the tool and is encountered with an error 1000:Target Closed. Is there any work around to make it multi user?

**Comment by lhhunghimself** [comment]
You can start multiple instances - however they must expose different ports on your host machine. 
For example:

docker run --rm   -p 6080:6080   -v  $pwd/:/data      -v  /var/run/docker.sock:/var/run/docker.sock     -v /tmp/.X11-unix:/tmp/.X11-unix     --privileged --group-add root biodepot/bwb

docker run --rm   -p 8080:6080   -v  $pwd/:/data      -v  /var/run/docker.sock:/var/run/docker.sock     -v /tmp/.X11-unix:/tmp/.X11-unix     --privileged --group-add root biodepot/bwb

starts two instances of Bwb, that you can connect to on using localhost:6080 and localhost:8080. 

Currently, it is not possible for two browsers to connect to the same instance of Bwb. It is possible to add this feature. It would require changing the nginx config to manage multiple users and launching multiple instances of the backend but I don't see much utility in this compared to launching two separate instances.

If you want a tool inside Bwb to interact multiple users - this should be possible since Bwb does export X11 GUIs from tools to the user, but you would have to open another port and manage the traffic yourself and allow Docker access to all your ports with a --net=host  flag when starting Bwb.

Hong

**Comment by pushkarbajaj9** [comment]
Thanks Hong for the quick reply. I did try to expose the tool on different ports to run different instances and it does get deployed successfully. I am using majorly jupyter notebook widgets and the issue is that jupyter notebook container is not able to differentiate between the two different instances on different ports. If i have a jupyter notebook already open in 6080 port instance and then try to open jupyter notebook from 8080 port instance, the notebook invoked from 8080 port still opens in the 6080 port.
