### ISSUE TITLE
W: --force-yes is deprecated, use one of the options starting with --allow instead.

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#20]
It looks like a couple of the Docker files include `apt-get --force-yes`.
https://github.com/BioDepot/BioDepot-workflow-builder/blob/995d8c61696bd8e1f35716f6b0b730c2ebed8847/Dockerfile#L9
https://github.com/BioDepot/BioDepot-workflow-builder/blob/995d8c61696bd8e1f35716f6b0b730c2ebed8847/Dockerfile-widgets#L9

This should maybe be replaced with one or more of the --allow flags according to the [apt-get man page](https://manpages.debian.org/stretch/apt/apt-get.8.en.html).  We can use `--allow-downgrades --allow-remove-essential --allow-change-held-packages` instead.

**Comment by lhhunghimself** [comment]
Hmm. OK good catch. 

The reason it is there is because in older Ubuntu/Debians it worked to ensure that the Dockerfile could be used for an unattended build (probably to avoid the annoying ask the user for the timezone prompt). It also might be a holdover from a cut and paste since we already have
ENV DEBIAN_FRONTEND="noninteractive" in the Dockerfile

Did you try replacing the old flag with the new ones to see if it built properly?

Hong

**Comment by rgschmitz1** [comment]
> Did you try replacing the old flag with the new ones to see if it built properly?
I'm testing out now, I'll report back shortly.

**Comment by rgschmitz1** [comment]
Looks like replacing `--force-yes` with `--allow-downgrades --allow-remove-essential --allow-change-held-packages`  appears to work. This seems pretty benign, I just thought I'd point it out since I happened to notice it.
